apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app
  labels:
    app: shopping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
      - name: shopping-container
        image: karthidevops01/shopping:v.28
        ports:
        - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  type: NodePort
  selector:
    app: shopping
  ports:
  - protocol: TCP
    port: 80           # External port
    targetPort: 8181   # Container port
    nodePort: 30081    # NodePort (must be between 30000–32767)
